/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AcompanhamentoRouteImport } from './routes/acompanhamento'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as CentralDeAjudaRouteImport } from './routes/central-de-ajuda'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as MissaoEValoresRouteImport } from './routes/missao-e-valores'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as RegulamentoProgramaRouteImport } from './routes/regulamento-programa'
import { Route as TermosECondicoesRouteImport } from './routes/termos-e-condicoes'
import { Route as TutoriaisRouteImport } from './routes/tutoriais'
import { Route as AcademyDesenvolvimentoPessoalRouteImport } from './routes/academy/desenvolvimento-pessoal'
import { Route as AcademyEmpreendedorismoRouteImport } from './routes/academy/empreendedorismo'
import { Route as AcademyGestaoFinanceiraRouteImport } from './routes/academy/gestao-financeira'
import { Route as AcademyMarketingDigitalRouteImport } from './routes/academy/marketing-digital'
import { Route as AcademyMentalidadeRouteImport } from './routes/academy/mentalidade'
import { Route as AcademyTrafegoRouteImport } from './routes/academy/trafego'
import { Route as AcademyVendasRouteImport } from './routes/academy/vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoRoute = AcompanhamentoRouteImport.update({
  id: '/acompanhamento',
  path: '/acompanhamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralDeAjudaRoute = CentralDeAjudaRouteImport.update({
  id: '/central-de-ajuda',
  path: '/central-de-ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoEValoresRoute = MissaoEValoresRouteImport.update({
  id: '/missao-e-valores',
  path: '/missao-e-valores',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulamentoProgramaRoute = RegulamentoProgramaRouteImport.update({
  id: '/regulamento-programa',
  path: '/regulamento-programa',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosECondicoesRoute = TermosECondicoesRouteImport.update({
  id: '/termos-e-condicoes',
  path: '/termos-e-condicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TutoriaisRoute = TutoriaisRouteImport.update({
  id: '/tutoriais',
  path: '/tutoriais',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyDesenvolvimentoPessoalRoute =
  AcademyDesenvolvimentoPessoalRouteImport.update({
    id: '/desenvolvimento-pessoal',
    path: '/desenvolvimento-pessoal',
    getParentRoute: () => AcademyRoute,
  } as any)
const AcademyEmpreendedorismoRoute = AcademyEmpreendedorismoRouteImport.update({
  id: '/empreendedorismo',
  path: '/empreendedorismo',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyGestaoFinanceiraRoute = AcademyGestaoFinanceiraRouteImport.update({
  id: '/gestao-financeira',
  path: '/gestao-financeira',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyMarketingDigitalRoute = AcademyMarketingDigitalRouteImport.update({
  id: '/marketing-digital',
  path: '/marketing-digital',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyMentalidadeRoute = AcademyMentalidadeRouteImport.update({
  id: '/mentalidade',
  path: '/mentalidade',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyTrafegoRoute = AcademyTrafegoRouteImport.update({
  id: '/trafego',
  path: '/trafego',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyVendasRoute = AcademyVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AcademyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/acompanhamento': typeof AcompanhamentoRoute
  '/atendimento': typeof AtendimentoRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/missao-e-valores': typeof MissaoEValoresRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/regulamento-programa': typeof RegulamentoProgramaRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/tutoriais': typeof TutoriaisRoute
  '/academy/desenvolvimento-pessoal': typeof AcademyDesenvolvimentoPessoalRoute
  '/academy/empreendedorismo': typeof AcademyEmpreendedorismoRoute
  '/academy/gestao-financeira': typeof AcademyGestaoFinanceiraRoute
  '/academy/marketing-digital': typeof AcademyMarketingDigitalRoute
  '/academy/mentalidade': typeof AcademyMentalidadeRoute
  '/academy/trafego': typeof AcademyTrafegoRoute
  '/academy/vendas': typeof AcademyVendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/acompanhamento': typeof AcompanhamentoRoute
  '/atendimento': typeof AtendimentoRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/missao-e-valores': typeof MissaoEValoresRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/regulamento-programa': typeof RegulamentoProgramaRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/tutoriais': typeof TutoriaisRoute
  '/academy/desenvolvimento-pessoal': typeof AcademyDesenvolvimentoPessoalRoute
  '/academy/empreendedorismo': typeof AcademyEmpreendedorismoRoute
  '/academy/gestao-financeira': typeof AcademyGestaoFinanceiraRoute
  '/academy/marketing-digital': typeof AcademyMarketingDigitalRoute
  '/academy/mentalidade': typeof AcademyMentalidadeRoute
  '/academy/trafego': typeof AcademyTrafegoRoute
  '/academy/vendas': typeof AcademyVendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/acompanhamento': typeof AcompanhamentoRoute
  '/atendimento': typeof AtendimentoRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/missao-e-valores': typeof MissaoEValoresRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/regulamento-programa': typeof RegulamentoProgramaRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/tutoriais': typeof TutoriaisRoute
  '/academy/desenvolvimento-pessoal': typeof AcademyDesenvolvimentoPessoalRoute
  '/academy/empreendedorismo': typeof AcademyEmpreendedorismoRoute
  '/academy/gestao-financeira': typeof AcademyGestaoFinanceiraRoute
  '/academy/marketing-digital': typeof AcademyMarketingDigitalRoute
  '/academy/mentalidade': typeof AcademyMentalidadeRoute
  '/academy/trafego': typeof AcademyTrafegoRoute
  '/academy/vendas': typeof AcademyVendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/acompanhamento'
    | '/atendimento'
    | '/central-de-ajuda'
    | '/como-funciona'
    | '/fale-conosco'
    | '/missao-e-valores'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/regulamento-programa'
    | '/termos-e-condicoes'
    | '/tutoriais'
    | '/academy/desenvolvimento-pessoal'
    | '/academy/empreendedorismo'
    | '/academy/gestao-financeira'
    | '/academy/marketing-digital'
    | '/academy/mentalidade'
    | '/academy/trafego'
    | '/academy/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/acompanhamento'
    | '/atendimento'
    | '/central-de-ajuda'
    | '/como-funciona'
    | '/fale-conosco'
    | '/missao-e-valores'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/regulamento-programa'
    | '/termos-e-condicoes'
    | '/tutoriais'
    | '/academy/desenvolvimento-pessoal'
    | '/academy/empreendedorismo'
    | '/academy/gestao-financeira'
    | '/academy/marketing-digital'
    | '/academy/mentalidade'
    | '/academy/trafego'
    | '/academy/vendas'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/acompanhamento'
    | '/atendimento'
    | '/central-de-ajuda'
    | '/como-funciona'
    | '/fale-conosco'
    | '/missao-e-valores'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/regulamento-programa'
    | '/termos-e-condicoes'
    | '/tutoriais'
    | '/academy/desenvolvimento-pessoal'
    | '/academy/empreendedorismo'
    | '/academy/gestao-financeira'
    | '/academy/marketing-digital'
    | '/academy/mentalidade'
    | '/academy/trafego'
    | '/academy/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AcompanhamentoRoute: typeof AcompanhamentoRoute
  AtendimentoRoute: typeof AtendimentoRoute
  CentralDeAjudaRoute: typeof CentralDeAjudaRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  MissaoEValoresRoute: typeof MissaoEValoresRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RegulamentoProgramaRoute: typeof RegulamentoProgramaRoute
  TermosECondicoesRoute: typeof TermosECondicoesRoute
  TutoriaisRoute: typeof TutoriaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento': {
      id: '/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/acompanhamento'
      preLoaderRoute: typeof AcompanhamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-de-ajuda': {
      id: '/central-de-ajuda'
      path: '/central-de-ajuda'
      fullPath: '/central-de-ajuda'
      preLoaderRoute: typeof CentralDeAjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao-e-valores': {
      id: '/missao-e-valores'
      path: '/missao-e-valores'
      fullPath: '/missao-e-valores'
      preLoaderRoute: typeof MissaoEValoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamento-programa': {
      id: '/regulamento-programa'
      path: '/regulamento-programa'
      fullPath: '/regulamento-programa'
      preLoaderRoute: typeof RegulamentoProgramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-e-condicoes': {
      id: '/termos-e-condicoes'
      path: '/termos-e-condicoes'
      fullPath: '/termos-e-condicoes'
      preLoaderRoute: typeof TermosECondicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutoriais': {
      id: '/tutoriais'
      path: '/tutoriais'
      fullPath: '/tutoriais'
      preLoaderRoute: typeof TutoriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/desenvolvimento-pessoal': {
      id: '/academy/desenvolvimento-pessoal'
      path: '/desenvolvimento-pessoal'
      fullPath: '/academy/desenvolvimento-pessoal'
      preLoaderRoute: typeof AcademyDesenvolvimentoPessoalRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/empreendedorismo': {
      id: '/academy/empreendedorismo'
      path: '/empreendedorismo'
      fullPath: '/academy/empreendedorismo'
      preLoaderRoute: typeof AcademyEmpreendedorismoRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/gestao-financeira': {
      id: '/academy/gestao-financeira'
      path: '/gestao-financeira'
      fullPath: '/academy/gestao-financeira'
      preLoaderRoute: typeof AcademyGestaoFinanceiraRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/marketing-digital': {
      id: '/academy/marketing-digital'
      path: '/marketing-digital'
      fullPath: '/academy/marketing-digital'
      preLoaderRoute: typeof AcademyMarketingDigitalRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/mentalidade': {
      id: '/academy/mentalidade'
      path: '/mentalidade'
      fullPath: '/academy/mentalidade'
      preLoaderRoute: typeof AcademyMentalidadeRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/trafego': {
      id: '/academy/trafego'
      path: '/trafego'
      fullPath: '/academy/trafego'
      preLoaderRoute: typeof AcademyTrafegoRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/vendas': {
      id: '/academy/vendas'
      path: '/vendas'
      fullPath: '/academy/vendas'
      preLoaderRoute: typeof AcademyVendasRouteImport
      parentRoute: typeof AcademyRoute
    }
  }
}

interface AcademyRouteChildren {
  AcademyDesenvolvimentoPessoalRoute: typeof AcademyDesenvolvimentoPessoalRoute
  AcademyEmpreendedorismoRoute: typeof AcademyEmpreendedorismoRoute
  AcademyGestaoFinanceiraRoute: typeof AcademyGestaoFinanceiraRoute
  AcademyMarketingDigitalRoute: typeof AcademyMarketingDigitalRoute
  AcademyMentalidadeRoute: typeof AcademyMentalidadeRoute
  AcademyTrafegoRoute: typeof AcademyTrafegoRoute
  AcademyVendasRoute: typeof AcademyVendasRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyDesenvolvimentoPessoalRoute: AcademyDesenvolvimentoPessoalRoute,
  AcademyEmpreendedorismoRoute: AcademyEmpreendedorismoRoute,
  AcademyGestaoFinanceiraRoute: AcademyGestaoFinanceiraRoute,
  AcademyMarketingDigitalRoute: AcademyMarketingDigitalRoute,
  AcademyMentalidadeRoute: AcademyMentalidadeRoute,
  AcademyTrafegoRoute: AcademyTrafegoRoute,
  AcademyVendasRoute: AcademyVendasRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AcompanhamentoRoute: AcompanhamentoRoute,
  AtendimentoRoute: AtendimentoRoute,
  CentralDeAjudaRoute: CentralDeAjudaRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  MissaoEValoresRoute: MissaoEValoresRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  RegulamentoProgramaRoute: RegulamentoProgramaRoute,
  TermosECondicoesRoute: TermosECondicoesRoute,
  TutoriaisRoute: TutoriaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
