/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcompanhamentoRouteImport } from './routes/acompanhamento'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as CentralDeAjudaRouteImport } from './routes/central-de-ajuda'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as MissaoEValoresRouteImport } from './routes/missao-e-valores'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as RegulamentoProgramaRouteImport } from './routes/regulamento-programa'
import { Route as TermosECondicoesRouteImport } from './routes/termos-e-condicoes'
import { Route as TutoriaisRouteImport } from './routes/tutoriais'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoRoute = AcompanhamentoRouteImport.update({
  id: '/acompanhamento',
  path: '/acompanhamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralDeAjudaRoute = CentralDeAjudaRouteImport.update({
  id: '/central-de-ajuda',
  path: '/central-de-ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoEValoresRoute = MissaoEValoresRouteImport.update({
  id: '/missao-e-valores',
  path: '/missao-e-valores',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulamentoProgramaRoute = RegulamentoProgramaRouteImport.update({
  id: '/regulamento-programa',
  path: '/regulamento-programa',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosECondicoesRoute = TermosECondicoesRouteImport.update({
  id: '/termos-e-condicoes',
  path: '/termos-e-condicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TutoriaisRoute = TutoriaisRouteImport.update({
  id: '/tutoriais',
  path: '/tutoriais',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/atendimento': typeof AtendimentoRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/missao-e-valores': typeof MissaoEValoresRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/regulamento-programa': typeof RegulamentoProgramaRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/tutoriais': typeof TutoriaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/atendimento': typeof AtendimentoRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/missao-e-valores': typeof MissaoEValoresRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/regulamento-programa': typeof RegulamentoProgramaRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/tutoriais': typeof TutoriaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/atendimento': typeof AtendimentoRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/missao-e-valores': typeof MissaoEValoresRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/regulamento-programa': typeof RegulamentoProgramaRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/tutoriais': typeof TutoriaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhamento'
    | '/atendimento'
    | '/central-de-ajuda'
    | '/como-funciona'
    | '/fale-conosco'
    | '/missao-e-valores'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/regulamento-programa'
    | '/termos-e-condicoes'
    | '/tutoriais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhamento'
    | '/atendimento'
    | '/central-de-ajuda'
    | '/como-funciona'
    | '/fale-conosco'
    | '/missao-e-valores'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/regulamento-programa'
    | '/termos-e-condicoes'
    | '/tutoriais'
  id:
    | '__root__'
    | '/'
    | '/acompanhamento'
    | '/atendimento'
    | '/central-de-ajuda'
    | '/como-funciona'
    | '/fale-conosco'
    | '/missao-e-valores'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/regulamento-programa'
    | '/termos-e-condicoes'
    | '/tutoriais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanhamentoRoute: typeof AcompanhamentoRoute
  AtendimentoRoute: typeof AtendimentoRoute
  CentralDeAjudaRoute: typeof CentralDeAjudaRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  MissaoEValoresRoute: typeof MissaoEValoresRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RegulamentoProgramaRoute: typeof RegulamentoProgramaRoute
  TermosECondicoesRoute: typeof TermosECondicoesRoute
  TutoriaisRoute: typeof TutoriaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento': {
      id: '/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/acompanhamento'
      preLoaderRoute: typeof AcompanhamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-de-ajuda': {
      id: '/central-de-ajuda'
      path: '/central-de-ajuda'
      fullPath: '/central-de-ajuda'
      preLoaderRoute: typeof CentralDeAjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao-e-valores': {
      id: '/missao-e-valores'
      path: '/missao-e-valores'
      fullPath: '/missao-e-valores'
      preLoaderRoute: typeof MissaoEValoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamento-programa': {
      id: '/regulamento-programa'
      path: '/regulamento-programa'
      fullPath: '/regulamento-programa'
      preLoaderRoute: typeof RegulamentoProgramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-e-condicoes': {
      id: '/termos-e-condicoes'
      path: '/termos-e-condicoes'
      fullPath: '/termos-e-condicoes'
      preLoaderRoute: typeof TermosECondicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutoriais': {
      id: '/tutoriais'
      path: '/tutoriais'
      fullPath: '/tutoriais'
      preLoaderRoute: typeof TutoriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanhamentoRoute: AcompanhamentoRoute,
  AtendimentoRoute: AtendimentoRoute,
  CentralDeAjudaRoute: CentralDeAjudaRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  MissaoEValoresRoute: MissaoEValoresRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  RegulamentoProgramaRoute: RegulamentoProgramaRoute,
  TermosECondicoesRoute: TermosECondicoesRoute,
  TutoriaisRoute: TutoriaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
